# -*- coding: utf-8 -*-
"""Proyecto PROM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1fQk_3tfqj2BuoQLg2PpSW2Bw6BaUsg
"""

# Saludo al almacenista
print("Hola Almacenista, dime cómo es el estado del inventario el día de hoy")

# Solicitar datos de inventario inicial
inventario_tubos_1_2_pulgada = int(input("¿Cantidad de tubos de 1/2 de pulgada en inventario? "))
inventario_tubos_1_pulgada = int(input("¿Cantidad de tubos de 1 pulgada en inventario? "))
inventario_tubos_1_4_pulgada = int(input("¿Cantidad de tubos de 1/4 de pulgada en inventario? "))
inventario_uniones_1_2_pulgada = int(input("¿Cantidad de uniones de 1/2 de pulgada en inventario? "))
inventario_uniones_1_pulgada = int(input("¿Cantidad de uniones de 1 pulgada en inventario? "))
inventario_uniones_1_4_pulgada = int(input("¿Cantidad de uniones de 1/4 de pulgada en inventario? "))
inventario_codos_1_2_pulgada = int(input("¿Cantidad de codos de 1/2 de pulgada en inventario? "))
inventario_codos_1_pulgada = int(input("¿Cantidad de codos de 1 pulgada en inventario? "))
inventario_codos_1_4_pulgada = int(input("¿Cantidad de codos de 1/4 de pulgada en inventario? "))
inventario_t_1_2_pulgada = int(input("¿Cantidad de T de 1/2 de pulgada en inventario? "))
inventario_t_1_pulgada = int(input("¿Cantidad de T de 1 pulgada en inventario? "))
inventario_t_1_4_pulgada = int(input("¿Cantidad de T de 1/4 de pulgada en inventario? "))

# Saludo al ingeniero
print("\nIngeniero, dime la siguiente información")

# Preguntas al ingeniero
tubo_trabajo = input("¿Con qué tipo de tubo se va a trabajar? (1/2, 1, 1/4): ")
longitud_matriz_agua = float(input("¿Cuánto es la longitud total de la matriz de agua? (en metros): "))
cambios_direccion = int(input("¿Cuántos cambios de dirección hay? "))
t_system = int(input("¿Cuántas T hay en el sistema? "))

# Conversión de tipo de tubo
if tubo_trabajo == "1/2":
    tubo_trabajo_pulgadas = 1/2
elif tubo_trabajo == "1":
    tubo_trabajo_pulgadas = 1
elif tubo_trabajo == "1/4":
    tubo_trabajo_pulgadas = 1/4
else:
    print("Tipo de tubo no válido. Usando tubo de 1/2 de pulgada por defecto.")
    tubo_trabajo_pulgadas = 1/2

# Cálculo de cantidad a usar de tubos
cantidad_tubos_a_usar = (longitud_matriz_agua / 6)
if longitud_matriz_agua % 6 != 0:
    cantidad_tubos_a_usar = int(cantidad_tubos_a_usar) + 1

# Cálculo de cantidad a usar de uniones
cantidad_uniones_a_usar = cantidad_tubos_a_usar - 1

# Cálculo de cantidad a usar de T
cantidad_t_a_usar = t_system

# Cálculo de cantidad a usar de codos (considerando 1 codo por cada cambio de dirección)
cantidad_codos_a_usar = cambios_direccion

# Actualizar el inventario restando las cantidades usadas
inventario_tubos_1_2_pulgada -= cantidad_tubos_a_usar if tubo_trabajo_pulgadas == 1/2 else 0
inventario_tubos_1_pulgada -= cantidad_tubos_a_usar if tubo_trabajo_pulgadas == 1 else 0
inventario_tubos_1_4_pulgada -= cantidad_tubos_a_usar if tubo_trabajo_pulgadas == 1/4 else 0

inventario_uniones_1_2_pulgada -= cantidad_uniones_a_usar if tubo_trabajo_pulgadas == 1/2 else 0
inventario_uniones_1_pulgada -= cantidad_uniones_a_usar if tubo_trabajo_pulgadas == 1 else 0
inventario_uniones_1_4_pulgada -= cantidad_uniones_a_usar if tubo_trabajo_pulgadas == 1/4 else 0

inventario_codos_1_2_pulgada -= cantidad_codos_a_usar if tubo_trabajo_pulgadas == 1/2 else 0
inventario_codos_1_pulgada -= cantidad_codos_a_usar if tubo_trabajo_pulgadas == 1 else 0
inventario_codos_1_4_pulgada -= cantidad_codos_a_usar if tubo_trabajo_pulgadas == 1/4 else 0

inventario_t_1_2_pulgada -= cantidad_t_a_usar if tubo_trabajo_pulgadas == 1/2 else 0
inventario_t_1_pulgada -= cantidad_t_a_usar if tubo_trabajo_pulgadas == 1 else 0
inventario_t_1_4_pulgada -= cantidad_t_a_usar if tubo_trabajo_pulgadas == 1/4 else 0

# Función para calcular la cantidad que falta comprar para alcanzar el mínimo establecido
def calcular_falta_comprar(cantidad_actual, cantidad_minima):
    falta_comprar = cantidad_minima - cantidad_actual
    return max(falta_comprar, 0)

# Calcular cuántos elementos faltan para alcanzar el mínimo en cada tipo
falta_comprar_tubos_1_2 = calcular_falta_comprar(inventario_tubos_1_2_pulgada, 5)
falta_comprar_tubos_1 = calcular_falta_comprar(inventario_tubos_1_pulgada, 5)
falta_comprar_tubos_1_4 = calcular_falta_comprar(inventario_tubos_1_4_pulgada, 5)

falta_comprar_uniones_1_2 = calcular_falta_comprar(inventario_uniones_1_2_pulgada, 5)
falta_comprar_uniones_1 = calcular_falta_comprar(inventario_uniones_1_pulgada, 5)
falta_comprar_uniones_1_4 = calcular_falta_comprar(inventario_uniones_1_4_pulgada, 5)

falta_comprar_codos_1_2 = calcular_falta_comprar(inventario_codos_1_2_pulgada, 10)
falta_comprar_codos_1 = calcular_falta_comprar(inventario_codos_1_pulgada, 10)
falta_comprar_codos_1_4 = calcular_falta_comprar(inventario_codos_1_4_pulgada, 10)

falta_comprar_t_1_2 = calcular_falta_comprar(inventario_t_1_2_pulgada, 10)
falta_comprar_t_1 = calcular_falta_comprar(inventario_t_1_pulgada, 10)
falta_comprar_t_1_4 = calcular_falta_comprar(inventario_t_1_4_pulgada, 10)

# Imprimir la cantidad de tubos, codos, uniones y T a usar
print("\nCantidad a usar según el tipo de tubería escogida:")
print(f"Tubos de {tubo_trabajo_pulgadas} de pulgada: {cantidad_tubos_a_usar}")
print(f"Codos de {tubo_trabajo_pulgadas} de pulgada: {cantidad_codos_a_usar} (90 grados)")
print(f"Uniones de {tubo_trabajo_pulgadas} de pulgada: {cantidad_uniones_a_usar}")
print(f"T de {tubo_trabajo_pulgadas} de pulgada: {cantidad_t_a_usar}")

# Imprimir los datos finales del inventario y las cantidades a comprar
print("\nInventario resultante:")
print(f"Tubos de 1/2 de pulgada: {max(inventario_tubos_1_2_pulgada, 5)} (Falta comprar: {falta_comprar_tubos_1_2})")
print(f"Tubos de 1 pulgada: {max(inventario_tubos_1_pulgada, 5)} (Falta comprar: {falta_comprar_tubos_1})")
print(f"Tubos de 1/4 de pulgada: {max(inventario_tubos_1_4_pulgada, 5)} (Falta comprar: {falta_comprar_tubos_1_4})")
print(f"Uniones de 1/2 de pulgada: {max(inventario_uniones_1_2_pulgada, 5)} (Falta comprar: {falta_comprar_uniones_1_2})")
print(f"Uniones de 1 pulgada: {max(inventario_uniones_1_pulgada, 5)} (Falta comprar: {falta_comprar_uniones_1})")
print(f"Uniones de 1/4 de pulgada: {max(inventario_uniones_1_4_pulgada, 5)} (Falta comprar: {falta_comprar_uniones_1_4})")
print(f"Codos de 1/2 de pulgada: {max(inventario_codos_1_2_pulgada, 10)} (Falta comprar: {falta_comprar_codos_1_2})")
print(f"Codos de 1 pulgada: {max(inventario_codos_1_pulgada, 10)} (Falta comprar: {falta_comprar_codos_1})")
print(f"Codos de 1/4 de pulgada: {max(inventario_codos_1_4_pulgada, 10)} (Falta comprar: {falta_comprar_codos_1_4})")
print(f"T de 1/2 de pulgada: {max(inventario_t_1_2_pulgada, 10)} (Falta comprar: {falta_comprar_t_1_2})")
print(f"T de 1 pulgada: {max(inventario_t_1_pulgada, 10)} (Falta comprar: {falta_comprar_t_1})")
print(f"T de 1/4 de pulgada: {max(inventario_t_1_4_pulgada, 10)} (Falta comprar: {falta_comprar_t_1_4})")

# Solicitar costo de materiales al almacenista
costo_tubos = float(input(f"¿Cuál es el costo de los tubos de {tubo_trabajo} de pulgada? "))
costo_uniones = float(input(f"¿Cuál es el costo de las uniones de {tubo_trabajo} de pulgada? "))
costo_codos = float(input(f"¿Cuál es el costo de los codos de {tubo_trabajo} de pulgada? "))
costo_t = float(input(f"¿Cuál es el costo de las T de {tubo_trabajo} de pulgada? "))

# Calculo del costo total del proyecto
costo_total_1 = (costo_tubos * falta_comprar_tubos_1) + (costo_uniones * falta_comprar_uniones_1) + (costo_codos * falta_comprar_codos_1) + (costo_t * falta_comprar_t_1)
costo_total_1_2 = (costo_tubos * falta_comprar_tubos_1_2) + (costo_uniones * falta_comprar_uniones_1_2) + (costo_codos * falta_comprar_codos_1_2) + (costo_t * falta_comprar_t_1_2)
costo_total_1_4 = (costo_tubos * falta_comprar_tubos_1_4) + (costo_uniones * falta_comprar_uniones_1_4) + (costo_codos * falta_comprar_codos_1_4) + (costo_t * falta_comprar_t_1_4)

costo_total = costo_total_1 + costo_total_1_2 + costo_total_1_4

# Imprimir los datos finales del costo total
print(f"El costo total del proyecto en la parte hidráulica por parte del inventario es de {costo_total} pesos colombianos")